---
firewall_vlan10_ip: "{{ firewall_vlan10_ip | default('192.168.10.1') }}"
firewall_vlan11_ip: "{{ firewall_vlan11_ip | default('192.168.11.1') }}"
firewall_vlan50_ip: "{{ firewall_vlan50_ip | default('192.168.50.1') }}"