---
- name: Déploiement du Pare-feu et préparation VPN / VLANs (Datacenter)
  hosts: firewall_dc
  become: yes

  roles:
    - firewall_dc

- name: Déploiement du serveur Sync-In
  hosts: syncin_dc
  become: yes
  roles:
    - syncin_dc