---
- name: Déploiement du Pare-feu et préparation VPN / VLANs (Datacenter)
  hosts: firewall
  become: yes

  roles:
    - firewall_dc

- name: Déploiement du serveur Nextcloud
  hosts: nextcloud
  become: yes
  roles:
    - nextcloud