---
- name: Déploiement du Pare-feu et préparation VPN / VLANs
  hosts: firewall
  become: yes

  roles:
    - firewall

- name: Déploiement du serveur Nextcloud
  hosts: nextcloud
  become: yes
  roles:
    - nextcloud